# This will run on Travis' 'new' container-based infrastructure
language: python
sudo: false 

python:
  - 3.7

virtualenv:
    system_site_package: true

before_install:
  - python --version
  - pip install -U pip
  - pip install -U -r requirements.txt

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

# Build your code e.g. by calling make
script:
  - python3 -m unittest discover
  - doxygen Doxyfile

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

notifications:
  webhooks: https://outlook.office.com/webhook/4d231d8b-6905-48b4-8918-d34c8f93e54c@3a5a8744-5935-45f9-9423-b32c3a5de082/TravisCI/b99a29a860f8425ca3ce641b904527d9/4f557b1a-2daf-4c64-b6c1-b32a4a7e1e41
